Scalars (Rank 0 Tensors) in base python

In [15]:
x=25

In [16]:
x

25

In [17]:
type(x) #if we want more specificity (e.g., int16, uint8), we need numpy or another numeric library

int

In [18]:
y=3

In [19]:
py_sum = x+y

In [20]:
py_sum

28

In [21]:
type(py_sum)

int

In [23]:
x_float = 25.0

In [25]:
float_sum = x_float + y

In [26]:
float_sum

28.0

In [27]:
type(float_sum)

float

pytorch lib is designed to be pythonic, like numpy.  pytorch tensors advantage relative to numpy is that it can be easily processed by gpus

In [3]:
import torch

In [2]:
print(torch.__version__)

2.3.1+cpu


In [4]:
x_pt=torch.tensor(25, dtype=torch.float16) #type specification optional, e.g.: dtype=torch.float16

In [5]:
x_pt

tensor(25., dtype=torch.float16)

In [6]:
x_pt.shape # has NO dimensions

torch.Size([])

In [7]:
import tensorflow as tf

In [9]:
x_tf = tf.Variable(25, dtype=tf.int16) #dtype is optional

In [10]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [11]:
x_tf.shape

TensorShape([])

In [12]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [13]:
x_tf+y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [14]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [20]:
tf_sum.numpy() #numpy operations automatically convert tensors to numpy arrays and vice versa

28

*author likes pytorch over tensorflow*

Vectors (Rank 1 Tensors) in NumPy

In [17]:
import numpy as np

In [19]:
x=np.array([25,2,5], dtype=np.float16) # typeis optional, e.g.: dtype=np.float16
x

array([25.,  2.,  5.], dtype=float16)

In [9]:
len(x)

3

In [11]:
x.shape

(3,)

In [12]:
type(x)

numpy.ndarray

In [13]:
x[0] # zero-indexed

25.0

In [14]:
type(x[0])

numpy.float16