Scalars (Rank 0 Tensors) in base python

In [4]:
x=25

In [5]:
x

25

In [6]:
type(x)

int

In [7]:
y=3

In [8]:
py_sum = x+y

In [9]:
py_sum

28

In [10]:
type(py_sum)

int

In [11]:
x_float = 25.0

In [12]:
float_sum = x_float + y

In [13]:
float_sum

28.0

In [14]:
type(float_sum)

float

pytorch lib is designed to be pythonic, like numpy.  pytorch tensors advantage relative to numpy is that it can be easily processed by gpus

In [15]:
import torch

In [16]:
print(torch.__version__)

2.3.1+cpu


In [17]:
x_pt=torch.tensor(25, dtype=torch.float16) #type specification optional, e.g.: dtype=torch.float16

In [18]:
x_pt

tensor(25., dtype=torch.float16)

In [19]:
x_pt.shape # has NO dimensions

torch.Size([])

In [20]:
import tensorflow as tf

In [21]:
x_tf = tf.Variable(25, dtype=tf.int16) #dtype is optional

In [22]:
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [23]:
x_tf.shape

TensorShape([])

In [24]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [25]:
x_tf+y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [26]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [27]:
tf_sum.numpy() #numpy operations automatically convert tensors to numpy arrays and vice versa

28

*author likes pytorch over tensorflow*

Vectors (Rank 1 Tensors) in NumPy

In [28]:
import numpy as np

In [29]:
x=np.array([25,2,5], dtype=np.float16) # typeis optional, e.g.: dtype=np.float16
x

array([25.,  2.,  5.], dtype=float16)

In [30]:
len(x)

3

In [31]:
x.shape

(3,)

In [32]:
type(x)

numpy.ndarray

In [33]:
x[0] # zero-indexed

25.0

In [34]:
type(x[0])

numpy.float16